### ISSUE TITLE
Cycle2 not working

### ISSUE THREAD

**Issue by kejso** [backdrop-contrib/views_slideshow_cycle2#1]
Hi,

I have installed module according to instructions, also installed libraries module and downloaded jquery.cycle2.js and placed it in sites/all/libraries/jquery.cycle2.

I have no errors, everything seems fine but when I create view and use Cycle2, no options appear. Also the view is not working (all slides are showing next to each other).

The older version of Cycle is working just fine.

Thanks for any advice!

**Comment by Graham-72** [comment]
Sorry to hear it isn't working. A couple of things you might try:
1. Have your libraries folder at /libraries/ rather than /sites/all/libraries/
2. If you have not already done this, add the div tags described under 'status' in README.md

If this still doesn't work, let me know here and I will check whether my test installation is working in Backdrop 1.5.1

**Comment by kejso** [comment]
Hi,
1. I have copied jquery.cycle2 folder to /libraries/ - NO CHANGE
2. I wrapped the image field of the slide in DIV with class "cycle-slideshow" - NO CHANGE

Any other advice please?

**Comment by Graham-72** [comment]
I have now checked and can confirm that my test installation is showing Cycle2 working in Backdrop 1.5.1. However, I don't think the module is yet good enough for serious use.

When configuring your view are you seeing the Cycle2 option appear in Format : Slideshow : Settings? Here are a couple of screenshots of my view configuration
![testslides2 content backdrop starter 1](https://cloud.githubusercontent.com/assets/10559274/20140825/38aa365a-a685-11e6-8928-94b4c87c8de2.png)

Selecting 'settings' shows this:
![testslides2 content backdrop starter](https://cloud.githubusercontent.com/assets/10559274/20140837/44273140-a685-11e6-8a4e-35a843a679eb.png)

I have given my page view the path /testslides2 and when I go to this I see Cycle2 working. My view gets the image files from a page I created and gave the path /test-slideshow-2 and when I go to this I see (of course) the individual images all displayed separately.

**Comment by kejso** [comment]
Hi,
Everything looks the same on my page. Cycle2 is loaded in view slideshow settings, but the output are just separated static images...

**Comment by Graham-72** [comment]
@kejso I don't know whether this screenshot might help to identify where the problem is. I am using Firefox and its 'inspect element' facility. This shows the code being produced by my view and the Javascript attached to div class="cycle-slideshow"

![cycle2screenshot](https://cloud.githubusercontent.com/assets/10559274/20141927/8d23555e-a68a-11e6-9eb4-d1c1af1e4d5c.png)

**Comment by kejso** [comment]
@Graham-72 Thank you, I am also using Firefox 'inspect element' feature. However I realized, I don't have any Javascript attached to my DIV container containing images...I dont understand. Here is screenshot: 
![screensht1_03](https://cloud.githubusercontent.com/assets/23308264/20171685/1f8f6692-a732-11e6-9b9f-f8685bf03bd6.jpg)

I also tried to create new slide page for testing. I have noticed that after setting output as Slideshow and after saving its settings I got this error message:

> Warning: file_get_contents(formoptions): failed to open stream: No such file or directory in backdrop_build_js_cache() (line 5296 of /nfsmnt/hosting2_1/7/5/756b8ff6-9407-4267-8aeb-d36a35549e5e/flosgarden.sk/sub/zahradkarstvo/core/includes/common.inc).
> 
> Warning: implode(): Invalid arguments passed in form_error() (line 1736 of /nfsmnt/hosting2_1/7/5/756b8ff6-9407-4267-8aeb-d36a35549e5e/flosgarden.sk/sub/zahradkarstvo/core/includes/form.inc).

**Comment by Graham-72** [comment]
@kejso Regarding the javascript, perhaps you could check whether the two extra javascript files are being loaded for this view page. If you use 'inspect element' in Firefox and then look under the tab 'Debugger' you should see a list of the javascript files that have been loaded for this page. In this list you should see both 'jquery.cycle2.js' and 'views_slideshow_cycle2.js' in the list.

Another way of checking is to look at the source code for the page and search (using find) for the mention of these files. If doing this it might be necessary not to have aggregation of javascript files turned on in 'performance'.

I'm afraid I don't know what the error message is telling you. I think it may be something to do with having aggregation of javascript files turned on. Might this be the case?

**Comment by kejso** [comment]
@Graham-72 I turned off the aggregation, checked the site and the .js files are showing in the list. Unfortunatelly, even with aggregation turned off the results are the same. Can I ask what theme are you using for test, what modules have you installed and the exact step by step tutorial for making tested view? (maybe there is some hassle between modules)

Once again thank you for your time. I am working on site for company I work for and picked up Backdrop because of nice performance and usability...the working carousel is one of the demands....

**Comment by Graham-72** [comment]
@kejso I have quite a few modules on this test site. So I think it would be best if I try installing it on a fresh test installation without other modules. This may take two or three days to do.

Is there a particular reason why you want to use cycle2 - presumably so that the result is responsive. I am still sticking with cycle (1) for my public sites at the moment because I have high confidence in it.

**Comment by kejso** [comment]
@Graham-72 Yes, reason is responsive design. 
Regarding Cycle (1), I have problem with it, when using pager the slideshow is not working...I also opended this issue here on Github:
[https://github.com/backdrop-contrib/views_slideshow/issues/2]
I have previously worked with Drupal 7 and made also one site in Drupal 8, but Backdrop seems more ligtweight for me, particularly in this case. Hovewer, functional Views Slideshow is a must for me :)

**Comment by Graham-72** [comment]
@kejso I have now installed Cycle 2 in a fresh test site and it is working, except for the image numbering and controls. You can view my result at www.cgwebdesign.uk/slideshow-test. The page I created to be the source of the image files is at www.cgwebdesign.uk/slideshow1. Please let me know if these links do not work.

This installation is Backdrop 1.5.1 with three extra modules: libraries, views_slideshow and views_slideshow_cycle2. A libraries folder contains: jquery.cycle/jquery.cycle.all.min.js, jquery.cycle2/jquery.cycle2.js

I created a content type 'slideshow' with an image field, allowing multiple images, then gave this page the alias slideshow1.

I created a view to display these images using cycle2. In this view I set the image field to have no label displayed and set its style as follows: tick 'customise field HTML', leave it as 'use default', tick 'create a CSS class' and set it to 'cycle-slideshow'; tick 'Customize field and label wrapper HTML' and set it to 'none'; remove tick from 'Add default classes'.

Also at 'Multiple field settings' I removed the default separator comma, leaving the field blank.

In the view format settings for 'Bottom widgets' I have ticked both 'controls' and 'slide counter' and they appear on the page but are not working so this needs fixing.

I hope you have success in achieving the same result. I look forward to hearing from you.

**Comment by kejso** [comment]
@Graham-72 OK, It seems that I found the source of problems. When I create the Slideshow following exact settings as you it works. The images loaded from one content type are changing.
However, what I wanted to do is to have content type with field e.g. "slider image" and to use this field in slideshow and also as a link to the rest of the content type. Imagine a slider, that you can click on and redirect to content. But the slideshow works for me only when it loads images from single node...
Probably I do something wrong...

**Comment by Graham-72** [comment]
@kejso Thanks for letting me know. What you are wanting to do is an interesting idea which I am going to think about. I will do some different testing.

**Comment by Graham-72** [comment]
@kejso I have found there is a patch to achieve responsive images in views_slideshow_cycle version 1 and I have it working on my test site, so I have submitted a PR to the backdrop-contrib views_slideshow repository. See https://github.com/backdrop-contrib/views_slideshow/issues/3

**Comment by Graham-72** [comment]
Cycle 2 now working.
