### ISSUE TITLE
Instructions Confusing, Module not working

### ISSUE THREAD

**Issue by auxiliaryjoel** [backdrop-contrib/views_slideshow_cycle2#11]
The requirements listed include a deprecated one (Libraries).
The instructions here :
https://github.com/backdrop-contrib/views_slideshow_cycle2/releases/tag/1.x-2.0.1
say that the libraries folder can be removed but then that causes a warning in Backdrop that it is missing.
This is because that folder is a requirement of Views Slideshow
However If I remove Views Slideshow, How can I use View Slideshow Cycle2, as it requires Views Slideshow doesn't it? 
Also, for some bizarre reason, once View Slideshow Cycle2 module is installed - then the "Settings" options in Views no longer opens as a popup but instead opens within same screen except out of view.

**Comment by auxiliaryjoel** [comment]
Update: also the warning while trying to set View Options states:
You need to install the jQuery Cycle2 plugin. Create a directory in sites/all/libraries called jquery.cycle2, and then copy jquery.cycle2.js or jquery.cycle2.min.js into it. You can find the plugin at http://jquery.malsup.com/cycle2.

But this contradicts the instructions here:
https://github.com/backdrop-contrib/views_slideshow_cycle2/releases/tag/1.x-2.0.1
which says:
The Cycle2 jQuery plugin files are now included in this module and will be loaded automatically.

**Comment by ghost** [comment]
> The requirements listed include a deprecated one (Libraries).

Where are you seeing Libraries listed as a requirement?

> The instructions ... say that the libraries folder can be removed

No, they say "You can remove the library files from your /libraries directory." Meaning, if you previously had the 'jquery.cycle2' library files stored in your 'libraries' directory, you can now delete the 'jquery.cycle2' files from your 'libraries' directory, but leave the 'libraries' directory intact as other modules may still need it.
You don't need to remove Views Slideshow, as that is indeed a dependency of this module.

> the "Settings" options in Views no longer opens as a popup

Can you please provide a screenshot of this issue so I can better understand what you're referring to?

> the warning while trying to set View Options states

Same here, can you provide a screenshot please? There should be no mention of that anywhere in this module anymore...

**Comment by auxiliaryjoel** [comment]
> > The requirements listed include a deprecated one (Libraries).
> 
> Where are you seeing Libraries listed as a requirement?
> 
> > The instructions ... say that the libraries folder can be removed
> 
> No, they say "You can remove the library files from your /libraries directory." Meaning, if you previously had the 'jquery.cycle2' library files stored in your 'libraries' directory, you can now delete the 'jquery.cycle2' files from your 'libraries' directory, but leave the 'libraries' directory intact as other modules may still need it.
> You don't need to remove Views Slideshow, as that is indeed a dependency of this module.
> 
> > the "Settings" options in Views no longer opens as a popup
> 
> Can you please provide a screenshot of this issue so I can better understand what you're referring to?
> 
> > the warning while trying to set View Options states
> 
> Same here, can you provide a screenshot please? There should be no mention of that anywhere in this module anymore...

Requirement for Libraries can be seen in details of Module when viewing it on the admin/modules/list modules page, here is a screenshot:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/12387409/56999120-41fe8380-6bf1-11e9-91ff-05342bc4aa42.png">

As you can also see from above Screenshot - the Views Slideshow is Required. And the Views Slideshow requires that there be a jquery.cycle folder and .js within the libraries/ folder.
So isn't that contradicting the statement that you don't need the cycle content to exist in that folder?(as Views Slideshow requires it, and Views Slideshow Cycle 2 requires Views Slideshow...?)

VIEWS:
if the jquery.cycle2 folder and js is not in the sites/all/libraries directory, then the VIEWS Slideshow/Settings option does not open/reveal settings.
Screenshot:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/12387409/56999366-29db3400-6bf2-11e9-8fc1-255f2d1ac985.png">
The red circled 'settings' link will not open/reveal itself. if I put the jquery.cycle2 folder back into sites/all/libraries - then I can access it 

Error Message
If I leave the jquery.cycle2 directory in the sites/all/libraries directory but remove the jquery.cycle2.min.js file form that folder, then the Views settings gives me this error:
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/12387409/56999448-80487280-6bf2-11e9-9e32-a918f26f8c81.png">

**Comment by auxiliaryjoel** [comment]
Also, in addition to my above comment, once the Views Slideshow Cycle2 module is installed and the jquery.cycle2 directory is in sites/all/libraries  then the Views / Slideshow /Settings options no longer popup, but instead they fall below the content on the page like this:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/12387409/56999487-b5ed5b80-6bf2-11e9-8d48-27ff0acdafd3.png">

**Comment by auxiliaryjoel** [comment]
sorry I accidentally closed this while commenting. I've reopened and my comments prior to close are still relevant.

**Comment by ghost** [comment]
The Views Slideshow module actually consists of two sub-modules: Views Slideshow (the API) and Views Slideshow Cycle. The API module is what Cycle2 depends on, and it doesn't require any libraries. Only the original Cycle sub-module requires the original jQuery Cycle library, but if you're using that, you don't need Cycle2. If you're using Cycle2, you should uninstall Views Slideshow Cycle to avoid confusion and potential issues.

Also, your screenshot shows you have version 1.0.0 of Cycle2 installed. This older version does depend on the Libraries module and directory files. But if you upgrade to version 1.0.2 then those dependencies are removed.

As for your other issues, they'll probably be fixed when you start using the right version of Cycle2.

**Comment by BWPanda** [comment]
The Views Slideshow module actually consists of two sub-modules: Views Slideshow (the API) and Views Slideshow Cycle. The API module is what Cycle2 depends on, and it doesn't require any libraries. Only the original Cycle sub-module requires the original jQuery Cycle library, but if you're using that, you don't need Cycle2. If you're using Cycle2, you should uninstall Views Slideshow Cycle to avoid confusion and potential issues.

Also, your screenshot shows you have version 1.0.0 of Cycle2 installed. This older version does depend on the Libraries module and directory files. But if you upgrade to version 1.0.2 then those dependencies are removed.

As for your other issues, they'll probably be fixed when you start using the right version of Cycle2.

**Comment by auxiliaryjoel** [comment]
> The Views Slideshow module actually consists of two sub-modules: Views Slideshow (the API) and Views Slideshow Cycle. The API module is what Cycle2 depends on, and it doesn't require any libraries. Only the original Cycle sub-module requires the original jQuery Cycle library, but if you're using that, you don't need Cycle2. If you're using Cycle2, you should uninstall Views Slideshow Cycle to avoid confusion and potential issues.
> 
> Also, your screenshot shows you have version 1.0.0 of Cycle2 installed. This older version does depend on the Libraries module and directory files. But if you upgrade to version 1.0.2 then those dependencies are removed.
> 
> As for your other issues, they'll probably be fixed when you start using the right version of Cycle2.

Hi @BWPanda I installed the module via Backdrops built-in module installer and that is the version that it provided me with. (Did this a couple of days ago). Why would that have given me an old install and how do I force it to give me a newer one?

**Comment by ghost** [comment]
Sorry, I should have said above that the latest version of Cycle2 is 2.0.1 (not 1.0.2).

I'm not very familiar with installing modules via the UI in Backdrop. I'd suggest uninstalling Cycle2 completely, then trying again. If you're still getting the wrong version, open an issue in the Backdrop queue: https://github.com/backdrop/backdrop-issues/issues

**Comment by auxiliaryjoel** [comment]
@BWPanda  Ok no worries I'll give that a go.  You mentioned you're not familiar with installing modules that way - how do you do it? (I'm happy to use a different method so just curious)

**Comment by ghost** [comment]
I install modules using Drush, Git or sometimes wget on my server.

**Comment by Graham-72** [comment]
At the moment Backdrop's built-in module installer is pre-selecting the wrong release for this module. However, it shows available releases and so you can select and install the latest one.
![Screenshot_2019-05-02 Select versions slideshow oliverhosting uk](https://user-images.githubusercontent.com/10559274/57058286-e68ecd00-6ca6-11e9-8d24-3d4e2144597f.png)

**Comment by auxiliaryjoel** [comment]
> At the moment Backdrop's built-in module installer is pre-selecting the wrong release for this module. However, it shows available releases and so you can select and install the latest one.
> ![Screenshot_2019-05-02 Select versions slideshow oliverhosting uk](https://user-images.githubusercontent.com/10559274/57058286-e68ecd00-6ca6-11e9-8d24-3d4e2144597f.png)

I've uninstalled Cycle2 from my List Modules, but when I try and install it again I cannot, it just says "Already downloaded" instead of the button for installing.
Anyone know how I can completely remove this and install it again (in order to select the different version)?

**Comment by auxiliaryjoel** [comment]
At first I was scared to delete the existing cylce2 directory from modules in case it corrupted any config settings. But I gave it a go - and it worked: I was able to reinstall and select the newer version.
Now the Cycle2 slider is transitioning between images.
Does anyone know how I can force the images to sit dead centre in the slide and always fill width and height proportionately?

**Comment by ghost** [comment]
@auxiliaryjoel I'd suggest searching https://github.com/malsup/cycle2/issues for help regarding positioning your images.

Closing this issue now that you got it working.
