### ISSUE TITLE
Module doesn't work

### ISSUE THREAD

**Issue by auxiliaryjoel** [backdrop-contrib/views_slideshow_cycle2#12]
After installation the images within the carousel no longer transition. Instead the first image remains in view and does not move.
If the module is uninstalled and the original "Views Slideshow" is used (with "Cycle" selected as the setting, as opposed to"Cycle2") then the carousel images begin to work as expected again.

**Comment by ghost** [comment]
I believe this is fixed, based on https://github.com/backdrop-contrib/views_slideshow_cycle2/issues/11.
