### ISSUE TITLE
Errors when editing view's Format: Settings

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/views_slideshow_cycle2#3]
I install the module and setup a slideshow view for the first time, then when I'm in the view and click Format > Settings, the following errors appear:

```
Warning: Invalid argument supplied for foreach() in _views_slideshow_cycle2_load_js() (line 83 of /[SNIP]/modules/views_slideshow_cycle2/views_slideshow_cycle2.module).
Notice: Undefined index: effect_options in views_slideshow_cycle2_effect_options() (line 21 of /[SNIP]/modules/views_slideshow_cycle2/views_slideshow_cycle2.plugins.inc).
```

The two errors don't appear to be related.

**Comment by ghost** [comment]
Then when I clicked on Fields > Add, I got the same two errors as above, plus these new ones:

```
Notice: Undefined index: remember_slide_days in views_slideshow_cycle2_views_slideshow_options_form_validate() (line 513 of /[SNIP]/modules/views_slideshow_cycle2/views_slideshow_cycle2.views_slideshow.inc).
Warning: implode(): Invalid arguments passed in form_error() (line 1736 of /[SNIP]/core/includes/form.inc).
```

**Comment by Graham-72** [comment]
@BWPanda is this now fixed? It seems to be thanks to your other PRs. If so, I will create a new release.

**Comment by ghost** [comment]
Nope, all errors were still appearing for me. PR addresses them though.

**Comment by Graham-72** [comment]
@BWPanda thanks again for these fixes. Please would you take over as maintainer for this module? The next step would seem to be to revise the README then make a new release. What do you think?

**Comment by ghost** [comment]
@Graham-72 Sure, I'll take it over. I might look over all the code and make a few other changes before making a new release, see if there's any way I can simplify things (less code = less maintenance 😉)
